### PR TITLE
WIP - don't merge! removes tiny-emitter as a mixin in favor of a module

### PR DESCRIPTION
**Pull request by sdellis**
@edsilv requiring tiny-emitter as a module (as I did in this PR) fixes the TinyEmitter undefined problem, but now I'm getting `ReferenceError: window is not defined` this is the param at the end of the anonymous function.  For unit tests, I actually don't want a window object, I just want to create an instance and test its methods.  I'm not sure how to move forward on the unit tests, but I need to move on with my project and can't spend much more time on this.  I figured you might have some insight.

### CODE REVIEW

**Comment by edsilv** [comment]
Could you create a new branch with these changes? Then I can try it out locally.

**Comment by edsilv** [comment]
Try putting `global` there instead of `window` - just a hunch.

**Comment by sdellis** [comment]
It worked! So, I had to change it to `global` in both base-component and the component-boilerplate-redux for it to run the boilerplate tests.  The examples work too.  Is there any repercussion to using `global` instead of `window`, or is it safe to roll with?

There is a [branch](https://github.com/viewdir/base-component/tree/tinyemitter-refactor).  I have not updated it yet with that change yet, but if `global` and `window` are interchangeable, then I can.

**Comment by edsilv** [comment]
I think if the example is working it's probably safe to roll with. We
should keep the changes on a branch and update the other components using
base-component#branch in their package.json. Once we're happy that all the
components work we can merge the changes to base component.

**Comment by sdellis** [comment]
@edsilv I just want to be clear that changing this param to `global` does not cause any problems in the other components.  The only time it would cause a problem is if unit tests are introduced.  I am cool with the plan you outlined if you think we should go through and update them all.

**Pull request merged**
